// Generated by Clause 3.5 Sonnet
function generateChildStory() {
  prompt.log("Welcome to the Interactive Child Story Generator!");

  // Step 1: Get story context from image (optional)
  let storyContext = prompt.boolean("Do you have an image for story context?");
  let imageDescription = "";
  if (storyContext) {
    imageDescription = prompt.vision(
      "Upload an image for story context:",
      "Describe the image in detail, focusing on elements that could be part of a children's story:"
    );
    prompt.log(`Image context: ${imageDescription}`);
  }

  // Step 2: Get child's age
  let childAge = prompt.number(
    "Enter the age of the child this story is for:",
    1,
    12
  );

  // Step 3: Get protagonist details
  let protagonistName = prompt.text(
    "Enter the name of the story's main character:",
    1,
    30
  );
  let protagonistTrait = prompt.text(
    `Enter one defining trait of ${protagonistName}:`,
    1,
    50
  );

  // Step 4: Get story setting
  let setting = prompt.text(
    "Enter a fun setting for the story (e.g., magical forest, space station):",
    1,
    100
  );

  // Step 5: Get a challenge or problem
  let challenge = prompt.text(
    `Enter a child-friendly challenge or problem for ${protagonistName} to face:`,
    1,
    150
  );

  // Step 6: Get a helper or magical element
  let helper = prompt.text(
    `Enter a helper or magical element that will assist ${protagonistName}:`,
    1,
    100
  );

  // Step 7: Generate the story
  prompt.log("\nGenerating your personalized story...\n");
  let storyPrompt = `
    Create an age-appropriate story for a ${childAge}-year-old child with the following elements:
    - Main character: ${protagonistName}, who is ${protagonistTrait}
    - Setting: ${setting}
    - Challenge: ${challenge}
    - Helper/Magical element: ${helper}
    ${imageDescription ? "- Additional context: " + imageDescription : ""}
    The story should be engaging, educational, and suitable for a ${childAge}-year-old.
    It should have a clear beginning, middle, and end, with a positive message or lesson learned.
    Keep the language and concepts appropriate for the child's age.
    `;
  let story = prompt.ai(storyPrompt);

  // Step 8: Display the story
  prompt.log("Your Personalized Story:\n");
  prompt.log(story);

  // Step 9: Optional story enhancement
  let enhance = prompt.boolean(
    "\nWould you like to enhance the story with an illustration prompt?"
  );
  if (enhance) {
    let illustrationPrompt = prompt.ai(
      `Based on the story above, create a prompt for an illustration that captures a key moment in the story. The prompt should be detailed and vivid, suitable for an artist to create an illustration for a children's book.`
    );
    prompt.log("\nIllustration Prompt:");
    prompt.log(illustrationPrompt);
  }

  prompt.log("\nThank you for using the Interactive Child Story Generator!");
}

// Run the story generator
generateChildStory();
