// LLMScript function Sudoku Solver 
// Generated by Claude 3.5 Sonnet
// "Write an LLMScript function to play the Soduko."

function solveSudoku(board) {
    const SIZE = 9;
    const EMPTY = 0;

    // Helper function to check if a number can be placed in a cell
    function isValid(num, row, col) {
        // Check row
        for (let x = 0; x < SIZE; x++) {
            if (board[row][x] === num) return false;
        }

        // Check column
        for (let x = 0; x < SIZE; x++) {
            if (board[x][col] === num) return false;
        }

        // Check 3x3 box
        let boxRow = Math.floor(row / 3) * 3;
        let boxCol = Math.floor(col / 3) * 3;
        for (let i = 0; i < 3; i++) {
            for (let j = 0; j < 3; j++) {
                if (board[boxRow + i][boxCol + j] === num) return false;
            }
        }

        return true;
    }

    // Recursive function to solve the Sudoku
    function solve() {
        for (let row = 0; row < SIZE; row++) {
            for (let col = 0; col < SIZE; col++) {
                if (board[row][col] === EMPTY) {
                    for (let num = 1; num <= SIZE; num++) {
                        if (isValid(num, row, col)) {
                            board[row][col] = num;
                            if (solve()) {
                                return true;
                            } else {
                                board[row][col] = EMPTY;
                            }
                        }
                    }
                    return false;
                }
            }
        }
        return true;
    }

    // Solve the Sudoku
    if (solve()) {
        return board;
    } else {
        return "No solution exists";
    }
}

// Function to print the Sudoku board
function printBoard(board) {
    let output = "";
    for (let i = 0; i < 9; i++) {
        if (i % 3 === 0 && i !== 0) {
            output += "- - - - - - - - - - - -\n";
        }
        for (let j = 0; j < 9; j++) {
            if (j % 3 === 0 && j !== 0) {
                output += "| ";
            }
            output += board[i][j] + " ";
        }
        output += "\n";
    }
    log(output);
}

// Example usage
let sudokuBoard = [
    [5, 3, 0, 0, 7, 0, 0, 0, 0],
    [6, 0, 0, 1, 9, 5, 0, 0, 0],
    [0, 9, 8, 0, 0, 0, 0, 6, 0],
    [8, 0, 0, 0, 6, 0, 0, 0, 3],
    [4, 0, 0, 8, 0, 3, 0, 0, 1],
    [7, 0, 0, 0, 2, 0, 0, 0, 6],
    [0, 6, 0, 0, 0, 0, 2, 8, 0],
    [0, 0, 0, 4, 1, 9, 0, 0, 5],
    [0, 0, 0, 0, 8, 0, 0, 7, 9]
];

log("Original Sudoku:");
printBoard(sudokuBoard);

let solvedBoard = solveSudoku(sudokuBoard);

log("\nSolved Sudoku:");
printBoard(solvedBoard);
