// LLMScript function solve24Puzzle
// Generated by Claude 3.5 Sonnet
// "Write an LLMScript function to solve the 24 puzzle."

function solve24Puzzle(numbers) {
    if (numbers.length !== 4) {
        return "Please provide exactly 4 numbers.";
    }

    const operators = ['+', '-', '*', '/'];
    const target = 24;
    const epsilon = 1e-6; // Small value to account for floating-point arithmetic errors

    function generateExpressions(nums) {
        if (nums.length === 1) {
            return [{value: nums[0], expression: nums[0].toString()}];
        }

        let results = [];
        for (let i = 0; i < nums.length; i++) {
            for (let j = i + 1; j < nums.length; j++) {
                let a = nums[i];
                let b = nums[j];
                let remainingNums = nums.filter((_, index) => index !== i && index !== j);

                for (let op of operators) {
                    let newValue, newExpression;
                    if (op === '+') {
                        newValue = a + b;
                        newExpression = `(${a} + ${b})`;
                    } else if (op === '-') {
                        newValue = a - b;
                        newExpression = `(${a} - ${b})`;
                    } else if (op === '*') {
                        newValue = a * b;
                        newExpression = `(${a} * ${b})`;
                    } else if (op === '/') {
                        if (Math.abs(b) < epsilon) continue; // Avoid division by zero
                        newValue = a / b;
                        newExpression = `(${a} / ${b})`;
                    }

                    let newNums = [...remainingNums, newValue];
                    let subResults = generateExpressions(newNums);
                    for (let subResult of subResults) {
                        results.push({
                            value: subResult.value,
                            expression: subResult.expression.replace(newValue.toString(), newExpression)
                        });
                    }

                    // Also try the reverse order for non-commutative operations
                    if (op === '-' || op === '/') {
                        if (op === '-') {
                            newValue = b - a;
                            newExpression = `(${b} - ${a})`;
                        } else {
                            if (Math.abs(a) < epsilon) continue; // Avoid division by zero
                            newValue = b / a;
                            newExpression = `(${b} / ${a})`;
                        }

                        newNums = [...remainingNums, newValue];
                        subResults = generateExpressions(newNums);
                        for (let subResult of subResults) {
                            results.push({
                                value: subResult.value,
                                expression: subResult.expression.replace(newValue.toString(), newExpression)
                            });
                        }
                    }
                }
            }
        }
        return results;
    }

    let allExpressions = generateExpressions(numbers);
    let solutions = allExpressions.filter(expr => Math.abs(expr.value - target) < epsilon);

    if (solutions.length === 0) {
        return "No solution found.";
    } else {
        return solutions.map(sol => sol.expression).join('\n');
    }
}

// Test the function with some examples
let testCases = [
    [4, 1, 8, 7],
    [1, 2, 3, 4],
    [6, 6, 6, 6],
    [3, 3, 8, 8],
    [5, 5, 5, 1]
];

for (let testCase of testCases) {
    log(`Solving 24 puzzle for numbers: ${testCase.join(', ')}`);
    log(solve24Puzzle(testCase));
    log(''); // Empty line for readability
}
