// LLMScript function solve24Puzzle
// Generated by Claude 3.5 Sonnet
// "Write an LLMScript function to solve the 24 puzzle."

function solve24(numbers) {
  let solutions = [];

  // Helper function to apply arithmetic operations
  function applyOperation(a, b, op) {
    switch (op) {
      case "+":
        return a + b;
      case "-":
        return a - b;
      case "*":
        return a * b;
      case "/":
        return b !== 0 ? a / b : null;
      default:
        return null;
    }
  }

  // Generate all permutations of the array (used for trying numbers in different orders)
  function permute(array) {
    if (array.length === 0) return [[]];
    return array.flatMap((v, i) =>
      permute([...array.slice(0, i), ...array.slice(i + 1)]).map((p) => [
        v,
        ...p,
      ])
    );
  }

  // Generate all pairs of numbers with all possible operations between them
  function generateExpressions(nums) {
    const results = [];
    for (let i = 0; i < nums.length; i++) {
      for (let j = 0; j < nums.length; j++) {
        if (i !== j) {
          const rest = nums.filter((_, index) => index !== i && index !== j);
          ["+", "-", "*", "/"].forEach((op) => {
            const res = applyOperation(nums[i], nums[j], op);
            if (res !== null) {
              results.push({
                result: res,
                rest: [...rest, res],
                expression: `(${nums[i]} ${op} ${nums[j]})`,
              });
            }
          });
        }
      }
    }
    return results;
  }

  // Recursive function to try all combinations of numbers and operations
  function trySolve(nums, expression = "") {
    if (nums.length === 1) {
      if (Math.abs(nums[0] - 24) < 1e-6) {
        solutions.push(expression || nums[0].toString());
      }
      return;
    }

    const expressions = generateExpressions(nums);
    for (const exp of expressions) {
      trySolve(
        exp.rest,
        expression ? `${expression} ${exp.expression}` : exp.expression
      );
    }
  }

  const permutations = permute(numbers);
  for (const perm of permutations) {
    trySolve(perm);
  }

  return solutions.length ? solutions : ["No solution"];
}

let testCases = [
  [4, 1, 8, 7],
  [1, 2, 3, 4],
  [6, 6, 6, 6],
  [3, 3, 8, 8],
  [5, 5, 5, 1],
];

for (let testCase of testCases) {
  PRINT(`Solving 24 puzzle for numbers: ${testCase.join(", ")}`);
  PRINT(solve24Puzzle(testCase));
  PRINT(""); // Empty line for readability
}
